applications/biblioteca/urls.py
from django.urls import path, re_path

from . import views

app_name = "biblioteca_app"

urlpatterns = [
    path('', views.ListaAutores.as_view(), name="lista-autores"),
    path('libros-autor/<pk>/', views.ListaLibrosAutores.as_view(), name="lista-libros"),
    # Añadimo la ruta nueva:
    path('autor/add', views.AddAutor.as_view(), name="autor-add")
]

applications/home/urls.py
from django.urls import path, re_path

app_name = "home_app"

from . import views

urlpatterns = [
    path('index', views.IndexView.as_view(), name="index"),
    # Introducimos la nueva url a la vista ListaLibros:
    path('libros', views.ListaLibros.as_view(), name="lista")
]

libro/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('applications.home.urls')),
    path('', include('applications.biblioteca.urls')), # Añadimos la ruta al archivo de rutas de biblioteca
    path('admin/', admin.site.urls),
]

applications/biblioteca/models.py
from django.db import models

class Autor(models.Model): 
    nombre = models.CharField('Nombres', max_length=80)
    nacionalidad = models.CharField(blank=True, max_length=100) 

    
    def __str__(self):
        return self.nombre 

# Creamos una nueva tabla:
class Libros(models.Model):
    title = models.CharField('Título', blank=False, max_length=150)
    resume = models.TextField('Resumen', blank=True) # Textfield admite un número indeterminado de caracteres
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE) # Creamos una clave foranea para vincular la tabla Autor con la tabla libros, le pasamos el parámetro on_delete obligatorio de modo que cuando se elimine un autor sus libros también se borrarán en cascada.

    def __str__(self):
        return self.title

applications/home/models.py
from django.db import models

# Create your models here.

applications/biblioteca/views.py
from django.shortcuts import render
from django.views.generic import(
    TemplateView,
    ListView,
    CreateView # Importamos una nueva vista generica para introducir datos
)

from .models import Autor, Libros

class ListaAutores(ListView):
    template_name = 'biblioteca/lista-autores.html'
    model = Autor
    context_object_name = 'autores'

class ListaLibrosAutores(ListView):
    template_name = 'biblioteca/lista-libros.html'
    model = Libros 
    context_object_name = 'libros'
    def get_queryset(self):
        id = self.kwargs['pk']
        lista = Libros.objects.filter( 
            autor = id
        )
        return lista

# vamos a crear la clase con la vista:
class AddAutor(CreateView):
    # Asigmanos el template:
    template_name = 'biblioteca/add-autor.html'
    # Ahora añadimos el modelo en el cual vamos a registrar al autor:
    model = Autor
    # Ahora vamos a solicitar los campos para hacer el registro:
    fields = ['nombre', 'nacionalidad']
    # Se recomienda establecer que va a pasar una vez se complete el registro:
    success_url = '/' # nos enviará a la ruta raiz.
    

applications/home/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView # Importamos la librería genérica Listview
)

class IndexView(TemplateView):
    template_name = "home/index.html"
    print('=============== URL de Prueba ================') 

# Esta vista es un poco más compleja que TemplateView:
class ListaLibros(ListView): #Creamos una clase que heredará de ListView
    template_name = "home/lista.html"
    # Creamos una lista manual asignandole a queryset un array:
    queryset = ['El quijote', 'El código da vinci', 'Oscuros', 'Sherlock Holmes']
    # Ahora vamos a establecer con que nombre vamos a manipular la lista de arriba:
    context_object_name = "libros"

templates/biblioteca/add-autor.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Agregar autor</title>
    </head>
    <body>
        <h1>Agregar autor</h1>
        <!-- Con este comando django nos mostrará el formulario automáticamente: --><!-- utilizamos un metodo post porque vamos a enviar, para traer se usa get -->
        <form method="post">{% csrf_token %} <!-- Añadimos el comando para envio seguro via post -->
            {{ form.as_p }}
            <!-- Añadimos el botón -->
            <button type="submit" name="button">Guardar</button>
        </form>
    </body>
</html>

templates/biblioteca/lista-autores.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Lista de autores</title>
    </head>
    <body>
        <h1>Autores registrados</h1>
        <table border="2">
            <thead>
                <th>Nombre</th>
                <th>Nacionalidad</th>
                <th>Acción</th>
            </thead>
            <tbody>
            {% for a in autores %}
                <tr>
                    <td>{{a.nombre}}</td>
                    <td>{{a.nacionalidad}}</td>
                    <!-- Ponemos la url de django en la propiedad href: -->
                    <td><a href="{% url 'biblioteca_app:lista-libros' a.id %}">VER</a></td><!-- usamos el app_name del archivo urls.py y la ruta, luego después de las comillas ponemos el id -->
                </tr>
            {% endfor %}
            </tbody>
        </table>
            
    </body>
</html>

templates/biblioteca/lista-libros.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Lista de libros por autor</h1>
        <!-- Creamos un bucle que mostrará todo el listado -->
        <table border="2">
            <thead>
                <th>ID</th>
                <th>Título</th>
                <th>Autor</th>
            </thead>
            <tbody>
            {% for l in libros %}
                <tr>
                    <td>{{l.id}}</td>
                    <td>{{l.title}}</td>
                    <td>{{l.autor}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </body>
</html>

templates/home/index.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Index de Home</h1>
    </body>
</html>

templates/home/lista.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Lista de libros</h1>
        <!-- Recuperamos con un bucle la información del listado -->
        <ul>
            {% for l in libros %}
                <li>{{l}}</li>
            {% endfor %}
        </ul>
    </body>
</html>